<?php

namespace App\Services;

use App\Models\Articles\ArticleImage;
use App\Models\Articles\ArticlePage;
use App\Models\Articles\Embedding;
use Auth;
use Log;
use OpenAI\Laravel\Facades\OpenAI;

class AIService
{
    /**
     * Generate a vector embedding for a given text using OpenAI.
     *
     * @param  string  $text  Input text.
     * @return array<float> Embedding vector values (empty array on failure).
     */
    public function generateEmbedding(string $text): array
    {
        $values = [];

        try {
            $result = OpenAI::embeddings()->create([
                'model' => 'text-embedding-3-small',
                'input' => $text,
            ]);

            $values = $result['data'][0]['embedding'];
        } catch (\Exception $e) {
            Log::info('Error in AIService->generateEmbedding', ['error' => $e->getMessage()]);
        }

        return $values;
    }

    /**
     * Answer a user’s question using retrieval-augmented generation (RAG).
     *
     * Workflow:
     *  1. Generate an embedding for the question.
     *  2. Search the database for the most relevant embeddings using pgvector.
     *  3. Collect context text from matching ArticlePages and ArticleImages.
     *  4. Send the question + context to GPT for an answer.
     *
     * @param  string  $question  The user’s natural language question.
     * @return array<string,mixed> [
     *                             'text'    => string Answer generated by GPT,
     *                             'sources' => array<int,array{id:int,type:string}> List of matched sources
     *                             ]
     */
    public function answerQuestion(string $question): array
    {
        $values = ['text' => '', 'sources' => []];

        try {
            // Step 1: Generate embedding for the question
            $qEmbedding = $this->generateEmbedding($question);
            $qEmbeddingStr = '['.implode(',', $qEmbedding).']';

            // Step 2: Build query with pgvector operator (<->)
            $query = Embedding::selectRaw(
                'embeddable_id, embeddable_type, embedding <-> ? as distance',
                [$qEmbeddingStr]
            )->orderBy('distance', 'asc');

            if (Auth::check()) {
                $user = Auth::user();

                // Filter embeddings by user’s articles
                $query->whereHasMorph(
                    'embeddable',
                    [ArticlePage::class, ArticleImage::class],
                    function ($q) use ($user) {
                        $q->whereHas('article', function ($qa) use ($user) {
                            // @phpstan-ignore-next-line
                            $qa->where('user_id', $user->id);
                        });
                    }
                );
            }

            $results = $query->limit(5)->get();

            // Step 3: Collect sources + context
            $sources = [];
            $context = '';

            foreach ($results as $embedding) {
                $sources[] = [
                    'id' => $embedding->embeddable_id,
                    'type' => class_basename($embedding->embeddable_type),
                ];

                // @phpstan-ignore-next-line
                $embeddable = $embedding->embeddable ?? null;

                if ($embeddable && ($embeddable instanceof ArticlePage || $embeddable instanceof ArticleImage)) {
                    $context .= "\n".($embeddable->native_text ?? '').' '.($embeddable->ocr_text ?? '');
                }
            }

            // Step 4: Ask GPT
            $completion = OpenAI::chat()->create([
                'model' => 'gpt-4o-mini',
                'messages' => [
                    ['role' => 'system', 'content' => 'You are a helpful assistant. Use only the provided context.'],
                    ['role' => 'user', 'content' => "Question: {$question}\n\nContext:\n{$context}"],
                ],
            ]);

            $answer = $completion['choices'][0]['message']['content'] ?? '';

            $values = [
                'text' => $answer,
                'sources' => $sources,
            ];
        } catch (\Exception $e) {
            Log::info('Error in AIService->answerQuestion', ['error' => $e->getMessage()]);
        }

        return $values;
    }
}
